version: '3.1'

services:
  backend:
    build: .
    command: uvicorn main:app --reload --port 8000 --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "8000:8000"


  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

  redis:
    image: redis
    ports:
      - "6379"

    volumes:
      - "/data"

